# Generated by Django 6.0.2 on 2026-04-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Designer',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mechanic',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('bgg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('primary_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('year_published', models.IntegerField(blank=True, null=True)),
                ('minimum_players', models.IntegerField(blank=True, null=True)),
                ('maximum_players', models.IntegerField(blank=True, null=True)),
                ('playing_time', models.IntegerField(blank=True, null=True)),
                ('minimum_playtime', models.IntegerField(blank=True, null=True)),
                ('maximum_playtime', models.IntegerField(blank=True, null=True)),
                ('minimum_age', models.IntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('average_rating', models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True)),
                ('bgg_rank', models.IntegerField(blank=True, null=True)),
                ('artists', models.ManyToManyField(blank=True, related_name='games', to='catalog.artist')),
                ('categories', models.ManyToManyField(blank=True, related_name='games', to='catalog.category')),
                ('designers', models.ManyToManyField(blank=True, related_name='games', to='catalog.designer')),
                ('families', models.ManyToManyField(blank=True, related_name='games', to='catalog.family')),
                ('mechanics', models.ManyToManyField(blank=True, related_name='games', to='catalog.mechanic')),
                ('publishers', models.ManyToManyField(blank=True, related_name='games', to='catalog.publisher')),
            ],
        ),
    ]
