# Generated by Django 6.1.1 on 2026-09-29 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0002_rebuild_play_session_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryitem",
            name="house_rules",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
    ]
