# Generated by Django 6.1.1 on 2026-10-06 00:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tracking", "0003_library_item_house_rules_not_null"),
    ]

    operations = [
        migrations.AddField(
            model_name="playsession",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
