# Generated by Django 6.1.1 on 2026-10-09 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_play_session_soft_delete'),
        ('tracking', '0006_library_item_remove_status'),
    ]

    operations = [
    ]
